// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV8jXu4ME8XgeYUufW_xRz-pvSIamZ_ts',
    appId: '1:482461771256:web:f94dd84cd8f4aedcc4e20d',
    messagingSenderId: '482461771256',
    projectId: 'amori-260523',
    authDomain: 'amori-260523.firebaseapp.com',
    storageBucket: 'amori-260523.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7fISUI-38MfscqWietCDA39uvM4CAiO0',
    appId: '1:482461771256:android:ce6b7cbb07d8c8f3c4e20d',
    messagingSenderId: '482461771256',
    projectId: 'amori-260523',
    storageBucket: 'amori-260523.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpjTfi018dBg4F6C_UZlo_GwwaZz9JJWk',
    appId: '1:482461771256:ios:992a597be8c6ded9c4e20d',
    messagingSenderId: '482461771256',
    projectId: 'amori-260523',
    storageBucket: 'amori-260523.firebasestorage.app',
    iosBundleId: 'com.example.amori',
  );
}
